version: "3.8"

services:
  auth1:
    build:
      context: ./services/auth-service
    restart: always
    environment:
      - PORT=4001
    expose:
      - "4001"
    env_file:
      - .env 
    depends_on:
      - db
      - redis
    networks:
      - app

  auth2:
    build:
      context: ./services/auth-service
    restart: always
    environment:
      - PORT=4002
    env_file:
      - .env 
    expose:
      - "4002"
    depends_on:
      - db
      - redis
    networks:
      - app

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - auth1
      - auth2
    networks:
      - app

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uni
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis
    networks:
      - app

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app

volumes:
  postgres_data:

networks:
  app:
